### ISSUE TITLE
*.scipy.org does not support any secure versions of TLS

### ISSUE THREAD

**Issue by kevin1** [scipy/scipy.org#128]
scipy.org and docs.scipy.org web servers only support SSL v3 and TLS v1.0, neither of which is secure. 

https://www.ssllabs.com/ssltest/analyze.html?d=docs.scipy.org

![screen shot 2015-11-21 at 11 14 27 pm](https://cloud.githubusercontent.com/assets/580013/11322040/a4cf0ab4-90a5-11e5-8170-2bca80ff9bc5.png)

The situation is so bad that my browser refuses to connect to the server — clicking the "numpy functions by category" link from numpy.org homepage gives this:

![screen shot 2015-11-21 at 11 13 33 pm](https://cloud.githubusercontent.com/assets/580013/11322038/8c446692-90a5-11e5-9181-8571628696c8.png)

**Comment by davidben** [comment]
The reason Safari doesn't load is probably because this site only enables DHE ciphers (but supporting TLS 1.2 would also be good). Chrome's intending to remove them later as well, so this should get resolved. See here:
https://groups.google.com/a/chromium.org/d/msg/security-dev/dYyhKHPnrI0/pNxx8vTKBAAJ

The site claims to be "Apache/2.2.16 (Debian)", Debian squeeze's version. You might want to start by upgrading to a more recent release. It's going to lose support very soon:
https://wiki.debian.org/LTS

**Comment by GiantCrocodile** [comment]
I would add a +1 to this. I can't read https://docs.scipy.org/doc because it doesn't support TLS 1.2 and lower versions aren't supported due to my browser's configuration.

**Comment by takluyver** [comment]
😠 I thought we had moved the site to a newer server, so I'm disappointed that this still affects it.

**Comment by PrabhanshuAttri** [comment]
How about using Cloudflare for SSL?

**Comment by kevin1** [comment]
Looks like they updated the TLS config so no need

<img width="1063" alt="screen shot 2017-11-19 at 7 33 20 pm" src="https://user-images.githubusercontent.com/580013/32997636-8bf51502-cd60-11e7-98b1-14e3ab8c9908.png">
