### ISSUE TITLE
cKDTree

### ISSUE THREAD

**Issue by yellowhat** [scipy/scipy.org#96]
Hi all,
I have two array (A,B) containing: ID, x, y, z of the same number of points but slightly differents.
I would like to have an array in which each row has the ID x y z of the two nearest points of the two array.
At the moment I have this:

import numpy as np
from scipy.spatial import cKDTree
A = np.loadtxt('A.txt')
B = np.loadtxt('B.txt')
tree = cKDTree( B[:,[1,2,3]] )
d, inds = tree.query( A[:,[1,2,3]], k=1, p=np.inf, eps=0.0)
A_new = A[inds]
xyz_near  = np.hstack(( B[:,0:4], A_new[:,0:4] ))

But the array "xyz_near" does not contain the right couple:
![image](https://cloud.githubusercontent.com/assets/1692490/8383711/429e0b5c-1c3c-11e5-8404-0b3419bf7d45.png)
As you can see the first two row are right but not the next three.

If I do the same thing in matlab with dsearchn:
![image](https://cloud.githubusercontent.com/assets/1692490/8383792/bf291068-1c3c-11e5-84d4-550c61634caa.png)
that is right.
I have tried to change p to 1, 2 and np.inf but same result.

Thanks

**Comment by rgommers** [comment]
Hi @yellowhat, this is the repo for the scipy.org website, not for the Scipy library (that would be https://github.com/scipy/scipy). However, since this is a query and not a bug report, the best places to ask are either the scipy-user mailing list (see http://scipy.org/scipylib/mailing-lists.html) or StackOverflow. Can you please ask there?
